[package]
name = "quicson"
version = "0.1.0"
authors = ["Michał Śledź <sledzson08@gmail.com>"]
edition = "2018"

[dependencies]
quiche = "0.3.0"
bincode = "1.1.4"
ring = "0.16.11"
log = "0.4.8"
env_logger = "0.7.1"
mio = "0.6"
url = "1"
curl = "0.4.29"
